### ISSUE TITLE
Any views are not rendered in Xcode playgrounds....

### ISSUE THREAD

**Issue by sonsongithub** [sonsongithub/numsw#16]
Why?
![screenshot](https://cloud.githubusercontent.com/assets/33768/23588989/0315f620-0209-11e7-8ac9-8e72485f317b.png)

**Comment by omochi** [comment]
Click 2 circle icon button on top right. (its called Associate view)
If it fails , reboot Xcode process is good. (`Cmd` + `Q`, not `W`)

**Comment by sonsongithub** [comment]
This issue will be closed after adding documents about this procedure.

**Comment by sonsongithub** [comment]
24fa10ee4c15b8963c91f6208f9eea4475b03922
