### ISSUE TITLE
サンプルコードを統一する．

### ISSUE THREAD

**Issue by sonsongithub** [sonsongithub/numsw#20]
面倒臭くなってきたから日本語でｗ
Playground Bookに書くサンプルコードと，sandbox中のサンプルコードが分散している．
playground bookを生成するときにsandbox中のサンプルコードから自動的に，Playground Bookのサンプルコードを生成するようにする．

**Comment by omochi** [comment]
#32 で実装しましたのでレビューをお願いします

**Comment by sonsongithub** [comment]
5e0b96b495ecd2bc6ba6fc6ddd8d1d55c959bf8d
