### ISSUE TITLE
Batch drawing

### ISSUE THREAD

**Issue by sonsongithub** [sonsongithub/numsw#7]
I want to gather some rendering scripts into only one plot view.

For example,
```
holdon()
plot(x,y)
plot(x1, y1)
sacatter(x1, y1)
holdoff()
```

**Comment by omochi** [comment]
Does this script render 3 data on 1 image grouping by `holdon` and `holdoff` ?
How do you think such like API. vvv

```
hold {
  plot(x, y)
  plot(x1, y1)
  scatter(x1, y1)
}
```

This design prevent mistake to pairing `holdon` and `holdoff`.

**Comment by sonsongithub** [comment]
Very swifty. Good.

**Comment by omochi** [comment]
@sonsongithub PRがマージされたので実装状況が確認できたらこのissueをcloseお願いします

**Comment by sonsongithub** [comment]
動かなかった・・・・・

```
do {
    let t = Matrix.range(from: 0.1, to: 10, stride: 0.01)
    let siny = log(t*1.5)
    let t1 = Matrix.range(from: -10, to: 10, stride: 0.01)
    let siny1 = tan(t1*0.2)
    hold {
        addLine(x: t.elements, y: siny.elements)
        addLine(x: t1.elements, y: siny1.elements)
    }
}
```

**Comment by omochi** [comment]
addLineとaddLine2は互換性のために古い挙動を踏襲している関係でholdと併用できません
addLineの代わりにplotとscatterを使ってください

**Comment by omochi** [comment]
確認してみます

**Comment by sonsongithub** [comment]
動いた！

**Comment by omochi** [comment]
こちらでも動きました。
ついでに、sandbox上だとエンバグしたので、直しておきました。　→ #24

**Comment by sonsongithub** [comment]
Fixed 5e197a0
