### ISSUE TITLE
まぁ，当面の内は，日本語でもいいか．

### ISSUE THREAD

**Issue by sonsongithub** [sonsongithub/numsw#8]
どう思う？

**Comment by omochi** [comment]
自分はgithubに英語で書き込む事もありますが作文にめちゃめちゃ時間を使ってしまうので、
必要がないなら日本語のほうが作業効率は上がります。
でも、ハッカソンのようなタイムスパンではないので、別に大丈夫な程度です。

成長して注目されてきたら、広くコントリビュートしてもらえるように、
英語に寄せたほうが良いとは思っています。

**Comment by t-ae** [comment]
ある程度方針が固まるまでは日本語で良いんじゃないかと思います。

**Comment by colorbox** [comment]
omochi さんの意見に賛同です
しばらくは日本語、ある程度整ってきたタイミングで英語に切り替えというのが良いかと

そうすると切替のタイミングとかどうしましょう？
 ver1.0.0 ないし ver0.1.0 が出たらとかですかね？

**Comment by sonsongithub** [comment]
議論はしばらく混合
ドキュメントは英語
でFA？

**Comment by omochi** [comment]
良いと思います
